coverage:
  round: down
  range: 55..100
  precision: 2
  status:
    patch: no
  ignore:
  - "gen/**"
  - "**/*.pb.go"
  - "**/*.pb.validate.go"
  - "./internal/server/repository/client/**"
  - "./internal/app/client/**"
  - "./internal/app/server/**"