@startuml Component Interaction Diagram for DataKeeper

actor User

User --> Client : Инициировать регистрацию (Email, Password)
Client --> Server : Запрос на регистрацию
alt Успешная регистрация
    Server --> Server : Обработать регистрацию
    Server --> Server : Сгенерировать OTP
    Server --> PostgreSQL : Сохранить OTP
    Server --> Server : Отправить OTP на Email
    Server --> User : OTP по Email
else Ошибка регистрации
    Server --> Client : Вернуть ошибку
    Client --> User : Показать ошибку
end

User --> Client : Ввести OTP
Client --> Server : Проверка OTP
alt OTP действителен
    Server --> PostgreSQL : Проверить OTP
    PostgreSQL --> Server : OTP действителен
    Server --> Client : Вернуть статус регистрации
    Client --> User : Показать статус регистрации
else OTP недействителен
    Server --> Client : Вернуть ошибку
    Client --> User : Показать ошибку
end

User --> Client : Инициировать вход (Email, Password)
Client --> Server : Запрос на вход
Server --> PostgreSQL : Проверка данных пользователя
alt Данные корректны
    PostgreSQL --> Server : Данные корректны
    Server --> Client : Отправить токен аутентификации
    Client --> User : Показать успешный вход
else Данные некорректны
    PostgreSQL --> Server : Данные некорректны
    Server --> Client : Вернуть ошибку
    Client --> User : Показать ошибку
end

User --> Client : Добавить/Обновить данные
Client --> Server : Запрос на хранение данных
Server --> MinIO : Сохранить данные
Server --> MongoDB : Сохранить метаинформацию
alt Успешное сохранение
    Server --> Client : Вернуть статус хранения
    Client --> User : Показать статус хранения
else Ошибка сохранения
    Server --> Client : Вернуть ошибку
    Client --> User : Показать ошибку
end

User --> Client : Запросить данные
Client --> Server : Запрос на получение данных
Server --> MinIO : Получить данные
Server --> MongoDB : Получить метаинформацию
alt Успешное извлечение
    Server --> Client : Вернуть данные
    Client --> User : Показать данные
else Ошибка извлечения
    Server --> Client : Вернуть ошибку
    Client --> User : Показать ошибку
end
@enduml