name: build binarys

on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:

  devopstest:
    runs-on: ubuntu-latest
    container: golang:1.22
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          ls -l
          sudo apt-get update
          sudo apt-get install -y libgtk-3-0

      - name: "Build Linux Binary"
        run: |
          mkdir -p ./bin/linux
          go build -o ./bin/linux/datakeeper ./cmd/client/main.go
          go build -o ./bin/linux/datakeeper-server ./cmd/server/main.go

      - name: "Build Windows Binary"
        run: |
          mkdir -p ./bin/win
          GOOS=windows GOARCH=amd64 go build -o ./bin/win/datakeeper.exe ./cmd/client/main.go
      
      - name: "Build MacOS Binary"
        run: |
          mkdir -p ./bin/mac
          GOOS=darwin GOARCH=amd64 go build -o ./bin/mac/datakeeper ./cmd/client/main.go
     
      - name: Upload Linux Binary
        uses: actions/upload-artifact@v4
        with:
          name: datakeeper-linux
          path: ./bin/linux/

      - name: Upload Windows Binary
        uses: actions/upload-artifact@v4
        with:
          name: datakeeper-windows
          path: ./bin/win/

      - name: Upload MacOS Binary
        uses: actions/upload-artifact@v4
        with:
          name: datakeeper-mac
          path: ./bin/mac/

      # - name: "Build"
      #   uses: actions/upload-artifact@v4
      #   run: |
      #     mkdir -p ./bin/linux
      #     mkdir -p ./bin/win
      #     mkdir -p ./bin/mac
      #     # build linux
      #     go build -ldflags "-X 'github.com/Arcadian-Sky/datakeeper/internal/cli.BuildTime=$(date +'%Y-%m-%d %H:%M')'" -o ./bin/linux/datakeeper cmd/client/main.go
      #     go build -o ../bin/linux/datakeeper-server cmd/server/main.go
      #     # build windows
      #     GOOS=windows GOARCH=amd64 go build -ldflags "-X 'github.com/Arcadian-Sky/datakeeper/internal/cli.BuildTime=$(date +'%Y-%m-%d %H:%M')'" -o ./bin/win/datakeeper.exe cmd/client/main.go
      #     # build mac amd64
      #     GOOS=darwin GOARCH=amd64 go build -ldflags "-X 'github.com/Arcadian-Sky/datakeeper/internal/cli.BuildTime=$(date +'%Y-%m-%d %H:%M')'" -o ./bin/mac/datakeeper cmd/client/main.go