name: Test and coverage

on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install dependencies
        run: |
              sudo apt-get clean
              sudo apt-get update
              sudo apt-get install -y libgtk-3-dev pkg-config
      - name: Run coverage
        # run: go test ./internal/... -timeout 30s -race -coverprofile=coverage.out -covermode=atomic
        run: go test ./internal/... -coverpkg=./internal/... -coverprofile=coverage.out -covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}